#ifndef CONFIG_H_IN
#define CONFIG_H_IN
#define PROJECT_NAME "libtusclient"
#define PROJECT_VERSION ""
#define PROJECT_VERSION_MAJOR 
#define PROJECT_VERSION_MINOR 
#define PROJECT_VERSION_PATCH 
#define PROJECT_DESCRIPTION ""
#define PROJECT_AUTHOR ""
#define PROJECT_AUTHOR_EMAIL ""
#define PROJECT_AUTHOR_WEBSITE ""
#define PROJECT_LICENSE ""
#define PROJECT_COPYRIGHT ""
#define PROJECT_TRADEMARK ""
#define PROJECT_COMPANY ""
#define PROJECT_COMPANY_NAME ""
#define PROJECT_COMPANY_ADDRESS ""
#define PROJECT_COMPANY_CITY ""
#define PROJECT_COMPANY_COUNTRY ""
#define PROJECT_COMPANY_PHONE ""
#define PROJECT_COMPANY_EMAIL ""
#define PROJECT_COMPANY_WEBSITE ""
#define PROJECT_COMPANY_ZIPCODE ""
#define PROJECT_COMPANY_FAX ""

#endif // CONFIG_H_IN
