# config.cmake

set(MY_CMAKE_PROJECT_NAME "libtusclient")
message(STATUS "MY_CMAKE_PROJECT_NAME set to: ${MY_CMAKE_PROJECT_NAME}")

set(MY_CMAKE_PROJECT_VERSION "1.0.0")
message(STATUS "MY_CMAKE_PROJECT_VERSION set to: ${MY_CMAKE_PROJECT_VERSION}")

set(MY_CMAKE_PROJECT_DESCRIPTION "Library implementing the tus protocol for resumable uploads")
message(STATUS "MY_CMAKE_PROJECT_DESCRIPTION set to: ${MY_CMAKE_PROJECT_DESCRIPTION}")

set(MY_CMAKE_PROJECT_HOMEPAGE "https://github.com/Cadons/libtusclient")
message(STATUS "MY_CMAKE_PROJECT_HOMEPAGE set to: ${MY_CMAKE_PROJECT_HOMEPAGE}")

set(MY_CMAKE_PROJECT_LICENSE "MIT")
message(STATUS "MY_CMAKE_PROJECT_LICENSE set to: ${MY_CMAKE_PROJECT_LICENSE}")

set(MY_CMAKE_PROJECT_VERSION-STRING "1.0")
message(STATUS "MY_CMAKE_PROJECT_VERSION-STRING set to: ${MY_CMAKE_PROJECT_VERSION-STRING}")

set(MY_CMAKE_PROJECT_SEMVER "1.0.0")
message(STATUS "MY_CMAKE_PROJECT_SEMVER set to: ${MY_CMAKE_PROJECT_SEMVER}")

